### ISSUE TITLE
Share to Notally

### ISSUE THREAD

**Issue by olexandrshpak** [OmGodse/Notally#14]
When I share a link to Notally, it would be great to generate a short preview and link to URL.
Example shared link to Notally and Google Keep:
![Screenshot_2020-05-24-17-19-27-493_com omgodse notally](https://user-images.githubusercontent.com/34886023/82756541-843dc880-9de3-11ea-8349-269df31476d8.jpg)
![Screenshot_2020-05-24-17-20-24-860_com google android keep](https://user-images.githubusercontent.com/34886023/82756544-84d65f00-9de3-11ea-9282-8fc93832241f.jpg)

**Comment by OmGodse** [comment]
I'm sorry but I don't think this is possible.

Generating a link preview will require us to obtain the `INTERNET` permission, which contrasts with my goal for Notally to have minimum (preferably zero) permissions.

It also makes it harder for people to believe that none of their data is being harvested or uploaded, since although the permission is implicitly granted by the system, it still shows up in the list of requested permissions.
