### ISSUE TITLE
change navbar color in the light theme

### ISSUE THREAD

**Issue by qw123wh** [OmGodse/Notally#17]
![5A824DE1-64F1-4F5B-ACD1-CB64F7798D47](https://user-images.githubusercontent.com/59417474/84565633-b13e2500-ad6a-11ea-95b3-b7e36444b3d3.jpeg)
![6FD9AF7B-262F-442A-B6F6-1832EFADDA8C](https://user-images.githubusercontent.com/59417474/84565634-b1d6bb80-ad6a-11ea-8244-6e0b54f75197.jpeg)

Hello currently in the light theme the navbar is black. I wish it was the same color as the light theme.  I'll leave you some screenshot to make you understand what I mean

**Comment by OmGodse** [comment]
Up until the latest update, the navigation bar was white in the light theme. However, that only looks good for apps that rely on bottom navigation.

When used for apps that have navigation inside a drawer, it looks inelegant when the drawer is opened and the rest of the layout is under a scrim. It also seems to cut off the notes in the middle, further exacerbating the inelegance.

That's why it's been removed.
