### ISSUE TITLE
[Feature request] New line under existing line

### ISSUE THREAD

**Issue by lazerleif** [OmGodse/Notally#19]
When i create a list and have for example five entries i cant add a line after the first one by pressing enter. I need to go to the end and make a new line and move it.

**Comment by OmGodse** [comment]
Unfortunately that's a feature which cannot be implemented. 

I could modify the behaviour such that if you press the enter key while on the 1st item, it'll automatically insert a new item in the 2nd place. 

However, then the user won't be able to navigate from one item to the next with the enter key. 

IMHO that's not worth it. That's why a new item is only added to the list upon pressing enter if you're on the last item. Otherwise the focus changes to the next item.
