### ISSUE TITLE
USES INTERNET DATA IN THE BACKGROUND ?

### ISSUE THREAD

**Issue by primarto** [OmGodse/Notally#23]
1. The application does ***NOT have any permissions*** 
_(0 permissions, no permission for internet access)_
2. In the system setting i ****turn off**** wifi, cellular and background DATA for Notally app immediately after installation

After a week of use, I notice that the application also runs the background and consumes internet data (73.73MB) see screenshot.
***HOW IS THIS POSSIBLE ?***

Let someone else check and say if it's the same with him.

Screenshot
![notally](https://user-images.githubusercontent.com/62907157/87868806-73e03f00-c989-11ea-9fc0-f6f29dd972f0.png)
![notally2](https://user-images.githubusercontent.com/62907157/87868814-7fcc0100-c989-11ea-8132-c6640e403180.png)

App version: 2.5
Android version: 10

**Comment by OmGodse** [comment]
There's one possible explanation for it.
Starting from around API 21 (Lollipop), If you have backup app data to Google Drive enabled in your settings, the OS automatically backs up all the files of your app periodically unless you explicitly opt out of it (Which I saw no reason too).

**Comment by primarto** [comment]
Dont have any backup, I use android without gapps.
The application is downloaded via F-droid ( Izzy on droid repo).
I still can't figure it out.

**Comment by OmGodse** [comment]
Do you any other backup service such as Titanium Backup?

**Comment by primarto** [comment]
I did a factory reset of the phone after a few days of installing this app, I am a normal user nothing out of the ordinary...

**Comment by IzzySoft** [comment]
@primarto As you've pinged me separately: You could use an app like Netguard to find out. I don't assume @OmGodse is doing anything shady. His explanation sounds reasonable – but so does your counter. Only way to make sure is using a tool watching network traffic independently. Or ask @OmGodse to include an "opt-out" option for that GDrive backup (as he sees that as only explanation).

To me it seems weird that an app without Internet permission and without root powers should be able to directly open sockets itself. It could of course utilize other apps (e.g. calling an intent of some web browser) – but then that other app would be the one producing the traffic.

A weird thing, and I have no explanation to it. As I wrote, I don't assume the app itself is the direct cause here – but I have no idea how it could enter those stats at all.

One last possibility, even if a bit remote: I see you've uninstalled several apps. Maybe you've installed Notally after that? Then it *could* happen that Notally got the UID of one of the uninstalled apps – and the traffic you see was really caused by the "previous owner" of that UID. In that case it should no longer show up for dates after July 19th – which due to the factory reset you can no longer check. But if you'd give it another try, it should no longer show up at all if my theory is correct.

**Comment by moriel5** [comment]
From my testing (I had just installed Notally yesterday from @IzzySoft's repo, no GMS here either), so far I have not had Notally use network data in the background at all, and the only permissions I could see with Privacy Guard (I'm using CRDroid on my Nexus 4) are Read Clipboard, Modify Clipboard, and Notification/Toast.

I believe that @IzzySoft's suggesting makes most sense, that it's probably due to the UID belonging to a previous app.

**Comment by syphoxy** [comment]
I can also confirm that Notally uses precisely zero bytes of network data in normal operation.

![Screenshot_20200725-174950](https://user-images.githubusercontent.com/234569/88453184-b8933b00-ce9f-11ea-86a1-283c6cdabfdc.png)

I think the prevailing theory that your system is miscategorizing another app's network traffic to Notally makes sense.

@primarto if you're really concerned, you can review the code yourself, and build the app and run it. all you need is Android Studio.

**Comment by OmGodse** [comment]
You all should relax. There's nothing _shady_ going on behind the scenes. There's not even a _single_ network call in the app. As @syphoxy has correctly said, if you're really concerned, build it yourself.

**Comment by primarto** [comment]
@IzzySoft   I think your theory is correct, it is possible that the application took an UID from another application that I uninstalled because I have two users on the phone. In the coming days, if I have time, I will do my best to install the same application and see if it leads to that.
@OmGodse  I'm not someone who knows how to check the code and I don't think the app does something behind the scenes that it shouldn't, I just stated what I Noticed, I like and use your app

**Comment by IzzySoft** [comment]
@primarto I'm not sure you will be able to reproduce the issue easily. I don't know how Android assigns UserIDs – but I'd wonder if the same app would get the same ID again (whic ID should the other app get if you didn't uninstall first?). But you could see if Notally turns up again without much uninstalling preceding its install. Best done on a clean device of course. Not sure what could lead to a reuse of "old IDs" either…
