### ISSUE TITLE
[Feature Request] Pin note to top of list/grid

### ISSUE THREAD

**Issue by marissarousseau** [OmGodse/Notally#43]
Sometimes I have notes which I need to constantly refer to. It would be nice to be able to pin them to them top of the list/grid of notes for easy access.

**Comment by OmGodse** [comment]
Pinning is under works right now. It'll be added in the next couple of updates.

**Comment by qw123wh** [comment]
Currently the notes are sorted by creation date, the most recent notes are at the top, while the oldest ones are at the bottom, perhaps an option in the settings “view by creation date, or view by edit ” ,could solve this problem, because doing so if a note you edit often even if it was created 1 year ago will always be on top.  Is this what you mean @marissarousseau ?
Or do you mean something different?

**Comment by marissarousseau** [comment]
@qw123wh I more so meant the ability to pin notes to the very top of the list, so that no matter what notes are created or edited in the future, the note that is pinned remains above the rest. 

An example of functionality which works this way is in Google Keep Notes.

**Comment by OmGodse** [comment]
@marissarousseau @qw123wh 

> I more so meant the ability to pin notes to the very top of the list, so that no matter what notes are created or edited in the future, the note that is pinned remains above the rest.

This is exactly how it's being implemented currently

**Comment by OmGodse** [comment]
A feature to pin notes has been added. You can either wait for it to roll out on the Play Store or get it from the [releases](https://github.com/OmGodse/Notally/releases/tag/v3.3) page now.
