### ISSUE TITLE
Widget Support

### ISSUE THREAD

**Issue by tlmnot** [OmGodse/Notally#52]
Small widget box that display a note.
![small text box](https://user-images.githubusercontent.com/57796317/103636442-43498d00-4f4a-11eb-8b8c-5bf30482bb31.png)

Shortcute to create a note quick way.
![shortcute widget](https://user-images.githubusercontent.com/57796317/103636143-dcc46f00-4f49-11eb-91f6-f6c9ae869752.png)

**Comment by OmGodse** [comment]
It was originally the plan to include a widget that displays a note but I scrapped that due to the Android's widget API being stuck in the Jellybean era. It's also extremely troublesome to constantly keep the widget in sync with changes to notes.

However, if you just want a shortcut to create a note, just long press the launcher icon and pin a shortcut that appears there to your home screen.
