### ISSUE TITLE
make it more like google keep + other stuff

### ISSUE THREAD

**Issue by KraXen72** [OmGodse/Notally#57]
make the app a bit more like google keep:
- add image support (where you can add images to notes)
- add link previews (like in google keep it makes a card if you put a link in the note)
- add import notes from google keep (backup: takeout.google.com gives a json of keep notes you could import into notally)
- add note colors like in google keep (like 10 colors so you can differentiate some notes)
- add ability to pin notes
  
and some more stuff:
- add export to markdown / plaintext with markdown formatting

**Comment by OmGodse** [comment]
Thanks for your suggestions but..

1) I'm not going to add image support. The purpose of Notally is to be a clean and _text based_ notes app.
2) Reasons for not adding link previews are explained in #14
3) I'll have to look into this
4) An issue for this already exists. Check #15
5) Ability to pin notes has been already added in v3.3
6) Unfortunately due to certain architectural decisions on my part, Markdown isn't supported. Check this [comment](https://github.com/OmGodse/Notally/issues/40#issuecomment-711222449) for details.

**Comment by KraXen72** [comment]
thanks for resonding.
