### ISSUE TITLE
Continuation of formatted text

### ISSUE THREAD

**Issue by paritosh9199** [OmGodse/Notally#61]
I am loving this app so far. But one thing I noticed is that once I format the text with a style I am unable to continue typing with the current formatting style, It resets back normal styled text. Can we make it so that we are able to continue typing with current formatting styles.

**Comment by OmGodse** [comment]
I'd actually considered the method you're suggesting when adding formatting options but editing rich text is hard enough on desktop, it's something even Word struggles with. It's even more difficult on mobile.

I'm not saying it couldn't be done, but such a mode would be very complex and prone to one off glitches. That's why I've chosen to go with a simple menu for the selected text.

**Comment by paritosh9199** [comment]
There are ways to get this properly done. When a style is applied and one continues writing, the applied stylings should be used. When multiple enters are pressed then the styles should switch back to default. As majority of WYSIWYG editors follow this, Can't something like this be done?

**Comment by OmGodse** [comment]
Conceptually it's extremely easy and straightforward. But actually implementing a WYSIWYG editor that works seamlessly on Android is another challenge altogether. That's why to keep both the code base and user experience simple, I've opted for a simple selection based editor.
